name: demixing
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia

create_default_packages:
  - pip
  - pytorch
  - torchaudio
  - cudatoolkit=11.1
  - ignite
  - tensorboard
  - tensorboardX
  - pysoundfile
  - tqdm
  - pip:
    - torch-optimizer
    - musdb
    - git+https://github.com/yoyololicon/norbert@batch-support