name: demixing
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.1
  - ignite
  - tensorboard
  - tensorboardX
  - pysoundfile
  - tqdm
  - jsonschema
  - pip:
    - torch-optimizer
    - musdb
    - torchinfo
    - julius
    - git+https://github.com/yoyololicon/norbert@batch-support
